### ISSUE TITLE
Allow Auth using IAM Role

### ISSUE THREAD

**Issue by mieliespoor** [Inedo/inedox-aws#21]
Currently this extension allow authentication to AWS to happen through Secret/Access Keys and IAM Instance Profiles. This means that Proget can't run in ECS using Fargate. 

Fargate requires an IAM Role and no Instance Profile exist, so we need to make use of AssumeRole Credentials instead.

**Comment by gdivis** [comment]
Thanks! It's merged and we'll probably deploy the extension later today.
